apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend-test
spec:
    replicas: 2
    selector:
        matchLabels:
            app: backend-test
    template:
        metadata:
            labels:
                app: backend-test
        spec:
            containers:
                - name: fastapi
                  image: nacho2407/backend-test
                  ports:
                      - containerPort: 80
                  envFrom:
                      - configMapRef:
                            name: backend-env
                  env:
                      - name: NODE_NAME
                        valueFrom:
                            fieldRef:
                                fieldPath: spec.nodeName
                  resources:
                      requests:
                          cpu: "1000m"
                      limits:
                          cpu: "2000m"

---

apiVersion: v1
kind: Service
metadata:
    name: backend-test
spec:
    type: NodePort
    selector:
        app: backend-test
    ports:
        - port: 80
          targetPort: 80
          nodePort: 30080

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: backend-test
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: backend-test
    minReplicas: 2
    maxReplicas: 4
    metrics:
        - type: Resource
          resource:
              name: cpu
              target:
                  type: Utilization
                  averageUtilization: 80
    behavior:
        scaleUp:
            stabilizationWindowSeconds: 0
            policies:
                - type: Pods
                  value: 1
                  periodSeconds: 60
        scaleDown:
            stabilizationWindowSeconds: 120
            policies:
                - type: Pods
                  value: 1
                  periodSeconds: 60
